add aliyun_ftasr api
SpeechColab/Leaderboard pull request #34
Opened 2022-08-04 08:01 UTC by Lizerui9926

2022-08-04 09:51 UTC, dophist commented on models/aliyun_ftasr_api_zh/asr_sdk.py
> +    accessKeyId = "您的AccessKey Id"
Credentials should not be filled in code like these.  Please refer to aliyun_api_zh model, load these credentials from secret files.

2022-08-04 09:52 UTC, dophist commented on models/aliyun_ftasr_api_zh/docker/Dockerfile
> +LABEL maintainer="jerry.jiayu.du@gmail.com"
fix maintainer email address

2022-08-04 10:02 UTC, dophist commented on models/aliyun_ftasr_api_zh/read_oss_file.py
> +    ossPath = "oss://example/wav/"
I'm kinda confused with this `ossPath`:
1. who own this bucket? is this bucket accessible from public? Some of SpeechIO test sets are not open-sourced yet, uploading files to a public oss path will leak those test sets.
2. even if this is an oss path filled by leaderboard caller, does it mean that leaderboard caller need to create this bucket and directory manually from Aliyun web-console? Things like these steps can not be automated within an automate pipeline.

2022-08-04 10:11 UTC, dophist commented on models/aliyun_ftasr_api_zh/read_oss_file.py
> +    ossPath = "oss://example/wav/"
Also, how is this OSS bucket charged? Does this mean the leaderboard caller need to maintain this bucket and pay for uploading plus 7x24 storage fees?

2022-08-05 00:28 UTC, dophist commented on models/aliyun_ftasr_api_zh/asr_sdk.py
> +with open('accessKeyId', 'r') as f:
please rename the credential secret to be consistent with https://github.com/SpeechColab/Leaderboard/blob/master/models/aliyun_api_zh/update_token.py#L16

2022-08-05 00:28 UTC, dophist commented on models/aliyun_ftasr_api_zh/asr_sdk.py
> +with open('accessKeySecret', 'r') as f:
same kind of renaming as above, refer to https://github.com/SpeechColab/Leaderboard/blob/master/models/aliyun_api_zh/update_token.py#L19

2022-08-08 11:32 UTC, dophist requested changes
Two things left: 

* For security reason, please remove `ossutil64` from your model image, and download it *from the official Aliyun url* in the code.  This avoid the docker env running a totally untrusted binary.  You can assume the testing machine is connected to domestic internet, and use things like wget, but make sure you add `wget` dependency in your Dockerfile.

* Also make sure you can successfully validate your model submission on your own machine with your own Aliyun credential, as described in HOW_TO_SUBMIT.md

2022-08-09 10:08 UTC, dophist reviewed
Looks good to me now.  Did you validate the submission on your own machine with you own Aliyun credential ?

2022-08-10 02:34 UTC, Lizerui9926 commented
> Looks good to me now. Did you validate the submission on your own machine with you own Aliyun credential ?

Yes, we have verified the pipeline on MINI and UNLOCKED SpeechIO test sets.

2022-08-10 04:13 UTC, merged